name: ci
on: push
jobs:
  test:
    runs-on: macOS-10.14
    steps:
      - uses: actions/checkout@v1
      - name: Switch Xcode to 11.1
        run: xcversion select 11.1
      - name: Generate Xcode project file
        run: swift package generate-xcodeproj
      - name: Build
        run: xcodebuild -scheme Forever-Package -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=13.1'
      - name: Test
        run: xcodebuild -scheme Forever-Package -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=13.1' test | xcpretty
